### ISSUE TITLE
The stock products which have zero items are not updating in real time

### ISSUE THREAD

**Issue by dmerinero** [CoreDumped-ETSISI/FridgeAPI_WEB#8]
In the use case that the user picks items from a product to zero and try discard one of them from his cart, the stock count does not updating.

**Comment by EnriqCG** [comment]
The specific logic that seems to be causing this issue is the conditional located in `public/js/store.js` inside ```updateStock()```.

```javascript
if (stock > 0)
    productStock.text(stock + quantity);
}
```

**Comment by dmerinero** [comment]
The logic from function `updateStock(productId, quantity)` was corrected at his if clause condition ( from '>' to '>='):

```javascript
function updateStock(productId, quantity) {
    let productStock = $('#' + productId).find('.badge');
    let stock = parseInt(productStock.text());
    if (stock >= 0)
        productStock.text(stock + quantity);
}
```
